server:
  port: 8082

spring:
  application:
    name: loan-origination-service
  threads:
    virtual:
      enabled: true

banking-data-service:
  base-url: http://localhost:8081

fraud-check-service:
  base-url: http://localhost:8083
  deadline-millis: 3000

notification-service:
  base-url: http://localhost:8084

